// Watermark preset configurations

import { WatermarkPreset } from '../types/watermark';

export const WATERMARK_PRESETS: WatermarkPreset[] = [
  {
    id: 'tile-pattern',
    name: 'Tile Pattern',
    description: 'Dense grid covering entire image',
    category: 'coverage',
    pattern: 'grid',
    density: 'dense',
    style: 'subtle',
    config: {
      count: 20,
      baseSize: { width: 120, height: 40 },
      sizeVariation: 0.1,
      opacityRange: { min: 0.15, max: 0.25 },
      rotationRange: { min: -15, max: 15 },
      spacing: 80,
    },
  },
  {
    id: 'corner-branding',
    name: 'Corner Branding',
    description: '4 watermarks in corners',
    category: 'pattern',
    pattern: 'corners',
    density: 'sparse',
    style: 'standard',
    config: {
      count: 4,
      baseSize: { width: 100, height: 35 },
      sizeVariation: 0,
      opacityRange: { min: 0.6, max: 0.6 },
      rotationRange: { min: 0, max: 0 },
    },
  },
  {
    id: 'diagonal-stripe',
    name: 'Diagonal Stripe',
    description: 'Watermarks along diagonal line',
    category: 'pattern',
    pattern: 'diagonal',
    density: 'moderate',
    style: 'standard',
    config: {
      count: 8,
      baseSize: { width: 110, height: 38 },
      sizeVariation: 0.15,
      opacityRange: { min: 0.3, max: 0.4 },
      rotationRange: { min: -45, max: -45 },
      spacing: 120,
    },
  },
  {
    id: 'scattered-protection',
    name: 'Scattered Protection',
    description: 'Random placement with varied sizes',
    category: 'pattern',
    pattern: 'scattered',
    density: 'moderate',
    style: 'standard',
    config: {
      count: 12,
      baseSize: { width: 100, height: 35 },
      sizeVariation: 0.4,
      opacityRange: { min: 0.25, max: 0.45 },
      rotationRange: { min: -30, max: 30 },
    },
  },
  {
    id: 'minimal-single',
    name: 'Minimal',
    description: 'Single centered watermark',
    category: 'coverage',
    pattern: 'center',
    density: 'sparse',
    style: 'subtle',
    config: {
      count: 1,
      baseSize: { width: 150, height: 50 },
      sizeVariation: 0,
      opacityRange: { min: 0.5, max: 0.5 },
      rotationRange: { min: 0, max: 0 },
    },
  },
  {
    id: 'border-guard',
    name: 'Border Guard',
    description: 'Watermarks along image edges',
    category: 'pattern',
    pattern: 'edges',
    density: 'moderate',
    style: 'standard',
    config: {
      count: 12,
      baseSize: { width: 90, height: 32 },
      sizeVariation: 0.1,
      opacityRange: { min: 0.35, max: 0.45 },
      rotationRange: { min: -10, max: 10 },
      spacing: 100,
    },
  },
  {
    id: 'photographer-style',
    name: 'Photographer',
    description: 'Small bottom-right signature',
    category: 'style',
    pattern: 'single',
    density: 'sparse',
    style: 'subtle',
    config: {
      count: 1,
      baseSize: { width: 120, height: 40 },
      sizeVariation: 0,
      opacityRange: { min: 0.7, max: 0.7 },
      rotationRange: { min: 0, max: 0 },
      alignment: 'right',
    },
  },
  {
    id: 'dense-grid',
    name: 'Dense Grid',
    description: 'Maximum coverage protection',
    category: 'density',
    pattern: 'grid',
    density: 'dense',
    style: 'prominent',
    config: {
      count: 30,
      baseSize: { width: 100, height: 35 },
      sizeVariation: 0.05,
      opacityRange: { min: 0.2, max: 0.3 },
      rotationRange: { min: -5, max: 5 },
      spacing: 60,
    },
  },
  {
    id: 'moderate-coverage',
    name: 'Moderate Coverage',
    description: 'Balanced protection',
    category: 'density',
    pattern: 'grid',
    density: 'moderate',
    style: 'standard',
    config: {
      count: 12,
      baseSize: { width: 110, height: 38 },
      sizeVariation: 0.1,
      opacityRange: { min: 0.3, max: 0.4 },
      rotationRange: { min: -10, max: 10 },
      spacing: 120,
    },
  },
  {
    id: 'large-watermarks',
    name: 'Large',
    description: 'Big, visible watermarks',
    category: 'size',
    pattern: 'scattered',
    density: 'sparse',
    style: 'prominent',
    config: {
      count: 6,
      baseSize: { width: 180, height: 60 },
      sizeVariation: 0.2,
      opacityRange: { min: 0.4, max: 0.6 },
      rotationRange: { min: -20, max: 20 },
    },
  },
  {
    id: 'small-watermarks',
    name: 'Small',
    description: 'Subtle, small watermarks',
    category: 'size',
    pattern: 'scattered',
    density: 'moderate',
    style: 'subtle',
    config: {
      count: 15,
      baseSize: { width: 70, height: 25 },
      sizeVariation: 0.15,
      opacityRange: { min: 0.25, max: 0.35 },
      rotationRange: { min: -15, max: 15 },
    },
  },
  {
    id: 'micro-watermarks',
    name: 'Micro',
    description: 'Tiny, barely visible watermarks',
    category: 'size',
    pattern: 'grid',
    density: 'dense',
    style: 'subtle',
    config: {
      count: 40,
      baseSize: { width: 50, height: 18 },
      sizeVariation: 0.1,
      opacityRange: { min: 0.15, max: 0.2 },
      rotationRange: { min: -5, max: 5 },
      spacing: 50,
    },
  },
];

export const PRESET_CATEGORIES = [
  { id: 'pattern', name: 'Pattern', icon: '🔲' },
];
