# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      { paths: [process.argv[1]] },
    )',
    __dir__
  ]
).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Chromica' do
  use_native_modules!

  use_react_native!(
    :path => "../node_modules/react-native",
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

post_install do |installer|
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |build_config|
      build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      build_config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end

  installer.pods_project.targets.each do |target|
    next unless target.name == 'RNShare'

    target.build_configurations.each do |build_config|
      raw_paths = build_config.build_settings['HEADER_SEARCH_PATHS']
      paths =
        if raw_paths.is_a?(String)
          raw_paths.split(/\s+/)
        else
          Array(raw_paths)
        end

      paths << '$(inherited)'
      paths << '$(PODS_ROOT)/Headers/Public/ReactCodegen'
      paths << '$(PODS_CONFIGURATION_BUILD_DIR)/React-Codegen'

      build_config.build_settings['HEADER_SEARCH_PATHS'] = paths.uniq
    end
  end
end