import type { Language, UiTranslations } from './translations';

type ProjectRow = readonly [
  duplicate: string,
  rename: string,
  renameTitle: string,
  renamePlaceholder: string,
  nameRequired: string,
  untitled: string,
  mixed: string,
  elementsCount: string,
  justNow: string,
  minutesAgo: string,
  hoursAgo: string,
  yesterday: string,
  today: string,
  daysAgo: string,
  copySuffix: string,
  selectedCount: string,
  deleteSelectedTitle: string,
  deleteSelectedMessage: string,
];

type ImagePickerRow = readonly [
  selectPhoto: string,
  loadingPhotos: string,
  availablePhotos: string,
  loadingYourPhotos: string,
  unableToLoadTitle: string,
  permissionMessage: string,
  openFailed: string,
];

type ExportRow = readonly [
  title: string,
  savedToPhotos: string,
  saveFailed: string,
  instagramNotInstalled: string,
  instagramInstall: string,
  instagramShareFailed: string,
  gallery: string,
  files: string,
  share: string,
];

type NotificationRow = readonly [title: string, description: string];

const defineUi = (
  error: string,
  projectsRow: ProjectRow,
  imagePickerRow: ImagePickerRow,
  exportRow: ExportRow,
  imageNotAvailable: string,
  notificationRow: NotificationRow,
): UiTranslations => {
  const [
    duplicate,
    rename,
    renameTitle,
    renamePlaceholder,
    nameRequired,
    untitled,
    mixed,
    elementsCount,
    justNow,
    minutesAgo,
    hoursAgo,
    yesterday,
    today,
    daysAgo,
    copySuffix,
    selectedCount,
    deleteSelectedTitle,
    deleteSelectedMessage,
  ] = projectsRow;
  const [
    selectPhoto,
    loadingPhotos,
    availablePhotos,
    loadingYourPhotos,
    unableToLoadTitle,
    permissionMessage,
    openFailed,
  ] = imagePickerRow;
  const [
    title,
    savedToPhotos,
    saveFailed,
    instagramNotInstalled,
    instagramInstall,
    instagramShareFailed,
    gallery,
    files,
    share,
  ] = exportRow;
  const [notificationTitle, notificationDescription] = notificationRow;

  return {
    error,
    projects: {
      duplicate,
      rename,
      renameTitle,
      renamePlaceholder,
      nameRequired,
      untitled,
      mixed,
      elementsCount,
      justNow,
      minutesAgo,
      hoursAgo,
      yesterday,
      today,
      daysAgo,
      copySuffix,
      selectedCount,
      deleteSelectedTitle,
      deleteSelectedMessage,
    },
    imagePicker: {
      selectPhoto,
      loadingPhotos,
      availablePhotos,
      loadingYourPhotos,
      unableToLoadTitle,
      permissionMessage,
      openFailed,
    },
    export: {
      title,
      savedToPhotos,
      saveFailed,
      instagramNotInstalled,
      instagramInstall,
      instagramShareFailed,
      gallery,
      files,
      share,
    },
    editor: { imageNotAvailable },
    notifications: {
      title: notificationTitle,
      description: notificationDescription,
    },
  };
};

export const uiDefaults: Record<Language, UiTranslations> = {
  en: defineUi(
    'Error',
    [
      'Duplicate', 'Rename', 'Rename Project', 'Enter project name',
      'Name cannot be empty', 'Untitled Project', 'Mixed', 'Elements: {count}',
      'Just now', '{count} min ago', '{count} hr ago', 'Yesterday', 'Today',
      '{count} days ago', 'Copy', '{count} selected', 'Delete Projects',
      'Delete {count} selected projects? This cannot be undone.',
    ],
    [
      'Select Photo', 'Loading photos...', 'Photos available: {count}',
      'Loading your photos...', 'Unable to Load Photos',
      'Please allow photo-library access and make sure photos are available.',
      'Failed to open photo library',
    ],
    [
      'Export', 'Image saved to Photos!', 'Failed to save image',
      'Instagram not installed', 'Please install Instagram to share.',
      'Failed to share to Instagram', 'Gallery', 'Files', 'Share',
    ],
    'Image not available',
    ['Notifications', 'Allow reminders in system notification settings'],
  ),
  ru: defineUi(
    'Ошибка',
    [
      'Создать копию', 'Переименовать', 'Переименовать проект', 'Введите название проекта',
      'Название не может быть пустым', 'Проект без названия', 'Микс', 'Элементов: {count}',
      'Только что', '{count} мин назад', '{count} ч назад', 'Вчера', 'Сегодня',
      '{count} дн назад', 'копия', 'Выбрано: {count}', 'Удалить проекты',
      'Удалить выбранные проекты ({count})? Это действие нельзя отменить.',
    ],
    [
      'Выбрать фото', 'Загрузка фото...', 'Доступно фото: {count}',
      'Загрузка ваших фото...', 'Не удалось загрузить фото',
      'Разрешите доступ к медиатеке и убедитесь, что в ней есть фотографии.',
      'Не удалось открыть медиатеку',
    ],
    [
      'Экспорт', 'Изображение сохранено в «Фото»', 'Не удалось сохранить изображение',
      'Instagram не установлен', 'Установите Instagram, чтобы поделиться.',
      'Не удалось поделиться в Instagram', 'Галерея', 'Файлы', 'Поделиться',
    ],
    'Изображение недоступно',
    ['Уведомления выключены', 'Включите их в системных настройках, чтобы получать напоминания.'],
  ),
  es: defineUi(
    'Error',
    [
      'Duplicar', 'Renombrar', 'Renombrar proyecto', 'Introduce el nombre del proyecto',
      'El nombre no puede estar vacío', 'Proyecto sin título', 'Mezcla', 'Elementos: {count}',
      'Ahora mismo', 'Hace {count} min', 'Hace {count} h', 'Ayer', 'Hoy',
      'Hace {count} días', 'Copia', '{count} seleccionados', 'Eliminar proyectos',
      '¿Eliminar los {count} proyectos seleccionados? Esta acción no se puede deshacer.',
    ],
    [
      'Seleccionar foto', 'Cargando fotos...', 'Fotos disponibles: {count}',
      'Cargando tus fotos...', 'No se pudieron cargar las fotos',
      'Permite el acceso a la fototeca y comprueba que haya fotos disponibles.',
      'No se pudo abrir la fototeca',
    ],
    [
      'Exportar', '¡Imagen guardada en Fotos!', 'No se pudo guardar la imagen',
      'Instagram no está instalado', 'Instala Instagram para compartir.',
      'No se pudo compartir en Instagram', 'Galería', 'Archivos', 'Compartir',
    ],
    'Imagen no disponible',
    ['Notificaciones', 'Permite recordatorios en los ajustes de notificaciones del sistema'],
  ),
  de: defineUi(
    'Fehler',
    [
      'Duplizieren', 'Umbenennen', 'Projekt umbenennen', 'Projektnamen eingeben',
      'Der Name darf nicht leer sein', 'Unbenanntes Projekt', 'Gemischt', 'Elemente: {count}',
      'Gerade eben', 'Vor {count} Min.', 'Vor {count} Std.', 'Gestern', 'Heute',
      'Vor {count} Tagen', 'Kopie', '{count} ausgewählt', 'Projekte löschen',
      '{count} ausgewählte Projekte löschen? Dies kann nicht rückgängig gemacht werden.',
    ],
    [
      'Foto auswählen', 'Fotos werden geladen...', 'Verfügbare Fotos: {count}',
      'Deine Fotos werden geladen...', 'Fotos konnten nicht geladen werden',
      'Erlaube den Zugriff auf die Fotomediathek und stelle sicher, dass Fotos vorhanden sind.',
      'Fotomediathek konnte nicht geöffnet werden',
    ],
    [
      'Exportieren', 'Bild in Fotos gespeichert!', 'Bild konnte nicht gespeichert werden',
      'Instagram ist nicht installiert', 'Installiere Instagram zum Teilen.',
      'Teilen auf Instagram fehlgeschlagen', 'Galerie', 'Dateien', 'Teilen',
    ],
    'Bild nicht verfügbar',
    ['Mitteilungen', 'Erinnerungen in den System-Mitteilungseinstellungen erlauben'],
  ),
  fr: defineUi(
    'Erreur',
    [
      'Dupliquer', 'Renommer', 'Renommer le projet', 'Saisissez le nom du projet',
      'Le nom ne peut pas être vide', 'Projet sans titre', 'Mixte', 'Éléments : {count}',
      'À l’instant', 'Il y a {count} min', 'Il y a {count} h', 'Hier', 'Aujourd’hui',
      'Il y a {count} jours', 'Copie', '{count} sélectionnés', 'Supprimer les projets',
      'Supprimer les {count} projets sélectionnés ? Cette action est irréversible.',
    ],
    [
      'Sélectionner une photo', 'Chargement des photos...', 'Photos disponibles : {count}',
      'Chargement de vos photos...', 'Impossible de charger les photos',
      'Autorisez l’accès à la photothèque et vérifiez que des photos sont disponibles.',
      'Impossible d’ouvrir la photothèque',
    ],
    [
      'Exporter', 'Image enregistrée dans Photos !', 'Impossible d’enregistrer l’image',
      'Instagram n’est pas installé', 'Installez Instagram pour partager.',
      'Impossible de partager sur Instagram', 'Galerie', 'Fichiers', 'Partager',
    ],
    'Image indisponible',
    ['Notifications', 'Autoriser les rappels dans les réglages système des notifications'],
  ),
  pt: defineUi(
    'Erro',
    [
      'Duplicar', 'Renomear', 'Renomear projeto', 'Digite o nome do projeto',
      'O nome não pode ficar vazio', 'Projeto sem título', 'Misturado', 'Elementos: {count}',
      'Agora mesmo', 'Há {count} min', 'Há {count} h', 'Ontem', 'Hoje',
      'Há {count} dias', 'Cópia', '{count} selecionados', 'Excluir projetos',
      'Excluir os {count} projetos selecionados? Esta ação não pode ser desfeita.',
    ],
    [
      'Selecionar foto', 'Carregando fotos...', 'Fotos disponíveis: {count}',
      'Carregando suas fotos...', 'Não foi possível carregar as fotos',
      'Permita o acesso à biblioteca e verifique se há fotos disponíveis.',
      'Não foi possível abrir a biblioteca de fotos',
    ],
    [
      'Exportar', 'Imagem salva em Fotos!', 'Não foi possível salvar a imagem',
      'Instagram não está instalado', 'Instale o Instagram para compartilhar.',
      'Não foi possível compartilhar no Instagram', 'Galeria', 'Arquivos', 'Compartilhar',
    ],
    'Imagem indisponível',
    ['Notificações', 'Permita lembretes nos ajustes de notificações do sistema'],
  ),
  ja: defineUi(
    'エラー',
    [
      '複製', '名前を変更', 'プロジェクト名を変更', 'プロジェクト名を入力',
      '名前を空にすることはできません', '名称未設定のプロジェクト', 'ミックス済み', '要素: {count}',
      'たった今', '{count}分前', '{count}時間前', '昨日', '今日',
      '{count}日前', 'コピー', '{count}件選択中', 'プロジェクトを削除',
      '選択した{count}件のプロジェクトを削除しますか？この操作は取り消せません。',
    ],
    [
      '写真を選択', '写真を読み込み中...', '利用可能な写真: {count}',
      '写真を読み込み中...', '写真を読み込めません',
      '写真ライブラリへのアクセスを許可し、写真があることを確認してください。',
      '写真ライブラリを開けませんでした',
    ],
    [
      '書き出す', '画像を写真に保存しました！', '画像を保存できませんでした',
      'Instagramがインストールされていません', '共有するにはInstagramをインストールしてください。',
      'Instagramに共有できませんでした', 'ギャラリー', 'ファイル', '共有',
    ],
    '画像を利用できません',
    ['通知', 'システムの通知設定でリマインダーを許可'],
  ),
  zh: defineUi(
    '错误',
    [
      '复制', '重命名', '重命名项目', '输入项目名称',
      '名称不能为空', '未命名项目', '已混合', '元素：{count}',
      '刚刚', '{count} 分钟前', '{count} 小时前', '昨天', '今天',
      '{count} 天前', '副本', '已选择 {count} 个', '删除项目',
      '删除选中的 {count} 个项目？此操作无法撤销。',
    ],
    [
      '选择照片', '正在加载照片...', '可用照片：{count}',
      '正在加载你的照片...', '无法加载照片',
      '请允许访问照片图库，并确保其中有可用照片。',
      '无法打开照片图库',
    ],
    [
      '导出', '图像已保存到“照片”！', '无法保存图像',
      '未安装 Instagram', '请安装 Instagram 后再分享。',
      '无法分享到 Instagram', '图库', '文件', '分享',
    ],
    '图像不可用',
    ['通知', '在系统通知设置中允许提醒'],
  ),
  ko: defineUi(
    '오류',
    [
      '복제', '이름 변경', '프로젝트 이름 변경', '프로젝트 이름 입력',
      '이름을 비워 둘 수 없습니다', '제목 없는 프로젝트', '믹스됨', '요소: {count}',
      '방금', '{count}분 전', '{count}시간 전', '어제', '오늘',
      '{count}일 전', '복사본', '{count}개 선택됨', '프로젝트 삭제',
      '선택한 프로젝트 {count}개를 삭제할까요? 이 작업은 취소할 수 없습니다.',
    ],
    [
      '사진 선택', '사진 불러오는 중...', '사용 가능한 사진: {count}',
      '사진을 불러오는 중...', '사진을 불러올 수 없음',
      '사진 보관함 접근을 허용하고 사용 가능한 사진이 있는지 확인하세요.',
      '사진 보관함을 열지 못했습니다',
    ],
    [
      '내보내기', '이미지를 사진에 저장했습니다!', '이미지를 저장하지 못했습니다',
      'Instagram이 설치되어 있지 않음', '공유하려면 Instagram을 설치하세요.',
      'Instagram에 공유하지 못했습니다', '갤러리', '파일', '공유',
    ],
    '이미지를 사용할 수 없음',
    ['알림', '시스템 알림 설정에서 미리 알림 허용'],
  ),
  uk: defineUi(
    'Помилка',
    [
      'Дублювати', 'Перейменувати', 'Перейменувати проєкт', 'Введіть назву проєкту',
      'Назва не може бути порожньою', 'Проєкт без назви', 'Мікс', 'Елементів: {count}',
      'Щойно', '{count} хв тому', '{count} год тому', 'Учора', 'Сьогодні',
      '{count} дн тому', 'Копія', 'Вибрано: {count}', 'Видалити проєкти',
      'Видалити вибрані проєкти ({count})? Цю дію неможливо скасувати.',
    ],
    [
      'Вибрати фото', 'Завантаження фото...', 'Доступно фото: {count}',
      'Завантаження ваших фото...', 'Не вдалося завантажити фото',
      'Дозвольте доступ до фототеки й переконайтеся, що в ній є фотографії.',
      'Не вдалося відкрити фототеку',
    ],
    [
      'Експорт', 'Зображення збережено у Фото!', 'Не вдалося зберегти зображення',
      'Instagram не встановлено', 'Установіть Instagram, щоб поділитися.',
      'Не вдалося поділитися в Instagram', 'Галерея', 'Файли', 'Поділитися',
    ],
    'Зображення недоступне',
    ['Сповіщення', 'Дозволити нагадування в системних налаштуваннях сповіщень'],
  ),
  ar: defineUi(
    'خطأ',
    [
      'تكرار', 'إعادة التسمية', 'إعادة تسمية المشروع', 'أدخل اسم المشروع',
      'لا يمكن أن يكون الاسم فارغًا', 'مشروع بلا عنوان', 'ممزوج', 'العناصر: {count}',
      'الآن', 'منذ {count} د', 'منذ {count} س', 'أمس', 'اليوم',
      'منذ {count} أيام', 'نسخة', 'تم تحديد {count}', 'حذف المشاريع',
      'حذف المشاريع المحددة ({count})؟ لا يمكن التراجع عن هذا الإجراء.',
    ],
    [
      'اختيار صورة', 'جارٍ تحميل الصور...', 'الصور المتاحة: {count}',
      'جارٍ تحميل صورك...', 'تعذر تحميل الصور',
      'اسمح بالوصول إلى مكتبة الصور وتأكد من توفر صور فيها.',
      'تعذر فتح مكتبة الصور',
    ],
    [
      'تصدير', 'تم حفظ الصورة في الصور!', 'تعذر حفظ الصورة',
      'Instagram غير مثبت', 'ثبّت Instagram للمشاركة.',
      'تعذرت المشاركة على Instagram', 'المعرض', 'الملفات', 'مشاركة',
    ],
    'الصورة غير متاحة',
    ['الإشعارات', 'السماح بالتذكيرات في إعدادات إشعارات النظام'],
  ),
  cs: defineUi(
    'Chyba',
    [
      'Duplikovat', 'Přejmenovat', 'Přejmenovat projekt', 'Zadejte název projektu',
      'Název nesmí být prázdný', 'Projekt bez názvu', 'Smíšené', 'Prvky: {count}',
      'Právě teď', 'Před {count} min', 'Před {count} h', 'Včera', 'Dnes',
      'Před {count} dny', 'Kopie', 'Vybráno: {count}', 'Smazat projekty',
      'Smazat vybrané projekty ({count})? Tuto akci nelze vrátit zpět.',
    ],
    [
      'Vybrat fotografii', 'Načítání fotografií...', 'Dostupné fotografie: {count}',
      'Načítání vašich fotografií...', 'Fotografie nelze načíst',
      'Povolte přístup ke knihovně fotografií a ujistěte se, že jsou fotografie dostupné.',
      'Knihovnu fotografií nelze otevřít',
    ],
    [
      'Exportovat', 'Obrázek byl uložen do Fotek!', 'Obrázek se nepodařilo uložit',
      'Instagram není nainstalován', 'Pro sdílení nainstalujte Instagram.',
      'Sdílení na Instagram se nezdařilo', 'Galerie', 'Soubory', 'Sdílet',
    ],
    'Obrázek není dostupný',
    ['Oznámení', 'Povolte připomenutí v systémovém nastavení oznámení'],
  ),
  da: defineUi(
    'Fejl',
    [
      'Dupliker', 'Omdøb', 'Omdøb projekt', 'Indtast projektnavn',
      'Navnet må ikke være tomt', 'Projekt uden titel', 'Blandet', 'Elementer: {count}',
      'Lige nu', 'For {count} min siden', 'For {count} t siden', 'I går', 'I dag',
      'For {count} dage siden', 'Kopi', '{count} valgt', 'Slet projekter',
      'Slet de {count} valgte projekter? Dette kan ikke fortrydes.',
    ],
    [
      'Vælg foto', 'Indlæser fotos...', 'Tilgængelige fotos: {count}',
      'Indlæser dine fotos...', 'Kunne ikke indlæse fotos',
      'Tillad adgang til fotobiblioteket, og sørg for, at der er fotos.',
      'Kunne ikke åbne fotobiblioteket',
    ],
    [
      'Eksportér', 'Billedet er gemt i Fotos!', 'Kunne ikke gemme billedet',
      'Instagram er ikke installeret', 'Installer Instagram for at dele.',
      'Kunne ikke dele på Instagram', 'Galleri', 'Filer', 'Del',
    ],
    'Billedet er ikke tilgængeligt',
    ['Notifikationer', 'Tillad påmindelser i systemets notifikationsindstillinger'],
  ),
  el: defineUi(
    'Σφάλμα',
    [
      'Διπλότυπο', 'Μετονομασία', 'Μετονομασία έργου', 'Εισαγάγετε όνομα έργου',
      'Το όνομα δεν μπορεί να είναι κενό', 'Έργο χωρίς τίτλο', 'Μίξη', 'Στοιχεία: {count}',
      'Μόλις τώρα', 'Πριν από {count} λεπτά', 'Πριν από {count} ώρες', 'Χθες', 'Σήμερα',
      'Πριν από {count} ημέρες', 'Αντίγραφο', 'Επιλέχθηκαν {count}', 'Διαγραφή έργων',
      'Διαγραφή των {count} επιλεγμένων έργων; Αυτή η ενέργεια δεν αναιρείται.',
    ],
    [
      'Επιλογή φωτογραφίας', 'Φόρτωση φωτογραφιών...', 'Διαθέσιμες φωτογραφίες: {count}',
      'Φόρτωση των φωτογραφιών σας...', 'Δεν ήταν δυνατή η φόρτωση φωτογραφιών',
      'Επιτρέψτε την πρόσβαση στη βιβλιοθήκη και βεβαιωθείτε ότι υπάρχουν φωτογραφίες.',
      'Δεν ήταν δυνατό το άνοιγμα της βιβλιοθήκης',
    ],
    [
      'Εξαγωγή', 'Η εικόνα αποθηκεύτηκε στις Φωτογραφίες!', 'Η εικόνα δεν αποθηκεύτηκε',
      'Το Instagram δεν είναι εγκατεστημένο', 'Εγκαταστήστε το Instagram για κοινοποίηση.',
      'Η κοινοποίηση στο Instagram απέτυχε', 'Συλλογή', 'Αρχεία', 'Κοινοποίηση',
    ],
    'Η εικόνα δεν είναι διαθέσιμη',
    ['Ειδοποιήσεις', 'Επιτρέψτε υπενθυμίσεις στις ρυθμίσεις ειδοποιήσεων συστήματος'],
  ),
  fi: defineUi(
    'Virhe',
    [
      'Monista', 'Nimeä uudelleen', 'Nimeä projekti uudelleen', 'Anna projektin nimi',
      'Nimi ei voi olla tyhjä', 'Nimetön projekti', 'Sekoitettu', 'Elementtejä: {count}',
      'Juuri nyt', '{count} min sitten', '{count} t sitten', 'Eilen', 'Tänään',
      '{count} päivää sitten', 'Kopio', '{count} valittu', 'Poista projektit',
      'Poistetaanko {count} valittua projektia? Tätä ei voi kumota.',
    ],
    [
      'Valitse kuva', 'Ladataan kuvia...', 'Kuvia saatavilla: {count}',
      'Ladataan kuviasi...', 'Kuvia ei voitu ladata',
      'Salli kuvakirjaston käyttö ja varmista, että kuvia on saatavilla.',
      'Kuvakirjastoa ei voitu avata',
    ],
    [
      'Vie', 'Kuva tallennettiin Kuviin!', 'Kuvaa ei voitu tallentaa',
      'Instagramia ei ole asennettu', 'Asenna Instagram jakaaksesi.',
      'Jakaminen Instagramiin epäonnistui', 'Galleria', 'Tiedostot', 'Jaa',
    ],
    'Kuva ei ole saatavilla',
    ['Ilmoitukset', 'Salli muistutukset järjestelmän ilmoitusasetuksissa'],
  ),
  fil: defineUi(
    'Error',
    [
      'I-duplicate', 'Palitan ang pangalan', 'Palitan ang pangalan ng proyekto', 'Ilagay ang pangalan ng proyekto',
      'Hindi maaaring walang laman ang pangalan', 'Proyektong walang pamagat', 'Pinaghalo', 'Mga elemento: {count}',
      'Ngayon lang', '{count} min ang nakalipas', '{count} oras ang nakalipas', 'Kahapon', 'Ngayon',
      '{count} araw ang nakalipas', 'Kopya', '{count} ang napili', 'Burahin ang mga proyekto',
      'Burahin ang {count} napiling proyekto? Hindi ito maaaring bawiin.',
    ],
    [
      'Pumili ng larawan', 'Nilo-load ang mga larawan...', 'Mga larawang available: {count}',
      'Nilo-load ang iyong mga larawan...', 'Hindi ma-load ang mga larawan',
      'Payagan ang access sa photo library at tiyaking may mga larawang available.',
      'Hindi mabuksan ang photo library',
    ],
    [
      'I-export', 'Na-save ang larawan sa Photos!', 'Hindi ma-save ang larawan',
      'Hindi naka-install ang Instagram', 'I-install ang Instagram para makapagbahagi.',
      'Hindi maibahagi sa Instagram', 'Gallery', 'Mga File', 'Ibahagi',
    ],
    'Hindi available ang larawan',
    ['Mga Notification', 'Payagan ang mga paalala sa system notification settings'],
  ),
  he: defineUi(
    'שגיאה',
    [
      'שכפול', 'שינוי שם', 'שינוי שם הפרויקט', 'הזנת שם הפרויקט',
      'השם לא יכול להיות ריק', 'פרויקט ללא שם', 'משולב', 'רכיבים: {count}',
      'עכשיו', 'לפני {count} דק׳', 'לפני {count} שעות', 'אתמול', 'היום',
      'לפני {count} ימים', 'עותק', 'נבחרו {count}', 'מחיקת פרויקטים',
      'למחוק את {count} הפרויקטים שנבחרו? לא ניתן לבטל פעולה זו.',
    ],
    [
      'בחירת תמונה', 'התמונות נטענות...', 'תמונות זמינות: {count}',
      'התמונות שלך נטענות...', 'לא ניתן לטעון תמונות',
      'יש לאפשר גישה לספריית התמונות ולוודא שיש תמונות זמינות.',
      'לא ניתן לפתוח את ספריית התמונות',
    ],
    [
      'ייצוא', 'התמונה נשמרה בתמונות!', 'לא ניתן לשמור את התמונה',
      'Instagram אינו מותקן', 'יש להתקין את Instagram כדי לשתף.',
      'לא ניתן לשתף ב-Instagram', 'גלריה', 'קבצים', 'שיתוף',
    ],
    'התמונה אינה זמינה',
    ['התראות', 'יש לאפשר תזכורות בהגדרות ההתראות של המערכת'],
  ),
  hi: defineUi(
    'त्रुटि',
    [
      'डुप्लिकेट', 'नाम बदलें', 'प्रोजेक्ट का नाम बदलें', 'प्रोजेक्ट का नाम दर्ज करें',
      'नाम खाली नहीं हो सकता', 'बिना शीर्षक का प्रोजेक्ट', 'मिश्रित', 'तत्व: {count}',
      'अभी', '{count} मिनट पहले', '{count} घंटे पहले', 'कल', 'आज',
      '{count} दिन पहले', 'कॉपी', '{count} चयनित', 'प्रोजेक्ट हटाएँ',
      'चुने गए {count} प्रोजेक्ट हटाएँ? इसे पूर्ववत नहीं किया जा सकता।',
    ],
    [
      'फ़ोटो चुनें', 'फ़ोटो लोड हो रही हैं...', 'उपलब्ध फ़ोटो: {count}',
      'आपकी फ़ोटो लोड हो रही हैं...', 'फ़ोटो लोड नहीं हो सकीं',
      'फ़ोटो लाइब्रेरी की अनुमति दें और सुनिश्चित करें कि फ़ोटो उपलब्ध हैं।',
      'फ़ोटो लाइब्रेरी नहीं खुल सकी',
    ],
    [
      'निर्यात', 'इमेज फ़ोटो में सेव हो गई!', 'इमेज सेव नहीं हो सकी',
      'Instagram इंस्टॉल नहीं है', 'शेयर करने के लिए Instagram इंस्टॉल करें।',
      'Instagram पर शेयर नहीं हो सका', 'गैलरी', 'फ़ाइलें', 'शेयर करें',
    ],
    'इमेज उपलब्ध नहीं है',
    ['सूचनाएँ', 'सिस्टम सूचना सेटिंग में रिमाइंडर की अनुमति दें'],
  ),
  hu: defineUi(
    'Hiba',
    [
      'Másolás', 'Átnevezés', 'Projekt átnevezése', 'Adja meg a projekt nevét',
      'A név nem lehet üres', 'Névtelen projekt', 'Kevert', 'Elemek: {count}',
      'Éppen most', '{count} perce', '{count} órája', 'Tegnap', 'Ma',
      '{count} napja', 'Másolat', '{count} kijelölve', 'Projektek törlése',
      'Törli a kijelölt {count} projektet? Ez nem vonható vissza.',
    ],
    [
      'Fotó kiválasztása', 'Fotók betöltése...', 'Elérhető fotók: {count}',
      'Fotóid betöltése...', 'A fotók nem tölthetők be',
      'Engedélyezze a fotókönyvtár elérését, és ellenőrizze, hogy vannak-e fotók.',
      'A fotókönyvtár nem nyitható meg',
    ],
    [
      'Exportálás', 'A kép mentve a Fotókba!', 'A kép mentése sikertelen',
      'Az Instagram nincs telepítve', 'A megosztáshoz telepítse az Instagramot.',
      'Az Instagram-megosztás sikertelen', 'Galéria', 'Fájlok', 'Megosztás',
    ],
    'A kép nem érhető el',
    ['Értesítések', 'Emlékeztetők engedélyezése a rendszer értesítési beállításaiban'],
  ),
  id: defineUi(
    'Kesalahan',
    [
      'Duplikat', 'Ganti nama', 'Ganti nama proyek', 'Masukkan nama proyek',
      'Nama tidak boleh kosong', 'Proyek tanpa judul', 'Campuran', 'Elemen: {count}',
      'Baru saja', '{count} mnt lalu', '{count} jam lalu', 'Kemarin', 'Hari ini',
      '{count} hari lalu', 'Salinan', '{count} dipilih', 'Hapus proyek',
      'Hapus {count} proyek yang dipilih? Tindakan ini tidak dapat dibatalkan.',
    ],
    [
      'Pilih foto', 'Memuat foto...', 'Foto tersedia: {count}',
      'Memuat foto Anda...', 'Tidak dapat memuat foto',
      'Izinkan akses galeri foto dan pastikan ada foto yang tersedia.',
      'Tidak dapat membuka galeri foto',
    ],
    [
      'Ekspor', 'Gambar disimpan ke Foto!', 'Gagal menyimpan gambar',
      'Instagram belum terpasang', 'Pasang Instagram untuk berbagi.',
      'Gagal berbagi ke Instagram', 'Galeri', 'File', 'Bagikan',
    ],
    'Gambar tidak tersedia',
    ['Notifikasi', 'Izinkan pengingat di pengaturan notifikasi sistem'],
  ),
  it: defineUi(
    'Errore',
    [
      'Duplica', 'Rinomina', 'Rinomina progetto', 'Inserisci il nome del progetto',
      'Il nome non può essere vuoto', 'Progetto senza titolo', 'Mix', 'Elementi: {count}',
      'Adesso', '{count} min fa', '{count} h fa', 'Ieri', 'Oggi',
      '{count} giorni fa', 'Copia', '{count} selezionati', 'Elimina progetti',
      'Eliminare i {count} progetti selezionati? L’azione non può essere annullata.',
    ],
    [
      'Seleziona foto', 'Caricamento foto...', 'Foto disponibili: {count}',
      'Caricamento delle tue foto...', 'Impossibile caricare le foto',
      'Consenti l’accesso alla libreria e verifica che siano disponibili delle foto.',
      'Impossibile aprire la libreria foto',
    ],
    [
      'Esporta', 'Immagine salvata in Foto!', 'Impossibile salvare l’immagine',
      'Instagram non è installato', 'Installa Instagram per condividere.',
      'Impossibile condividere su Instagram', 'Galleria', 'File', 'Condividi',
    ],
    'Immagine non disponibile',
    ['Notifiche', 'Consenti i promemoria nelle impostazioni di notifica del sistema'],
  ),
  ms: defineUi(
    'Ralat',
    [
      'Duplikasi', 'Namakan semula', 'Namakan semula projek', 'Masukkan nama projek',
      'Nama tidak boleh kosong', 'Projek tanpa tajuk', 'Campuran', 'Elemen: {count}',
      'Baru sahaja', '{count} min lalu', '{count} jam lalu', 'Semalam', 'Hari ini',
      '{count} hari lalu', 'Salinan', '{count} dipilih', 'Padam projek',
      'Padam {count} projek yang dipilih? Tindakan ini tidak boleh dibuat asal.',
    ],
    [
      'Pilih foto', 'Memuatkan foto...', 'Foto tersedia: {count}',
      'Memuatkan foto anda...', 'Tidak dapat memuatkan foto',
      'Benarkan akses pustaka foto dan pastikan foto tersedia.',
      'Tidak dapat membuka pustaka foto',
    ],
    [
      'Eksport', 'Imej disimpan ke Foto!', 'Tidak dapat menyimpan imej',
      'Instagram tidak dipasang', 'Pasang Instagram untuk berkongsi.',
      'Tidak dapat berkongsi ke Instagram', 'Galeri', 'Fail', 'Kongsi',
    ],
    'Imej tidak tersedia',
    ['Pemberitahuan', 'Benarkan peringatan dalam tetapan pemberitahuan sistem'],
  ),
  nl: defineUi(
    'Fout',
    [
      'Dupliceren', 'Naam wijzigen', 'Projectnaam wijzigen', 'Voer de projectnaam in',
      'De naam mag niet leeg zijn', 'Naamloos project', 'Gemengd', 'Elementen: {count}',
      'Zojuist', '{count} min geleden', '{count} uur geleden', 'Gisteren', 'Vandaag',
      '{count} dagen geleden', 'Kopie', '{count} geselecteerd', 'Projecten verwijderen',
      '{count} geselecteerde projecten verwijderen? Dit kan niet ongedaan worden gemaakt.',
    ],
    [
      'Foto selecteren', 'Foto’s laden...', 'Beschikbare foto’s: {count}',
      'Je foto’s laden...', 'Foto’s konden niet worden geladen',
      'Sta toegang tot de fotobibliotheek toe en controleer of er foto’s beschikbaar zijn.',
      'Fotobibliotheek kon niet worden geopend',
    ],
    [
      'Exporteren', 'Afbeelding opgeslagen in Foto’s!', 'Afbeelding kon niet worden opgeslagen',
      'Instagram is niet geïnstalleerd', 'Installeer Instagram om te delen.',
      'Delen op Instagram is mislukt', 'Galerij', 'Bestanden', 'Delen',
    ],
    'Afbeelding niet beschikbaar',
    ['Meldingen', 'Sta herinneringen toe in de systeeminstellingen voor meldingen'],
  ),
  no: defineUi(
    'Feil',
    [
      'Dupliser', 'Gi nytt navn', 'Gi prosjektet nytt navn', 'Skriv inn prosjektnavn',
      'Navnet kan ikke være tomt', 'Prosjekt uten navn', 'Blandet', 'Elementer: {count}',
      'Akkurat nå', 'For {count} min siden', 'For {count} t siden', 'I går', 'I dag',
      'For {count} dager siden', 'Kopi', '{count} valgt', 'Slett prosjekter',
      'Slette de {count} valgte prosjektene? Dette kan ikke angres.',
    ],
    [
      'Velg bilde', 'Laster bilder...', 'Tilgjengelige bilder: {count}',
      'Laster bildene dine...', 'Kunne ikke laste bilder',
      'Tillat tilgang til bildebiblioteket, og kontroller at bilder er tilgjengelige.',
      'Kunne ikke åpne bildebiblioteket',
    ],
    [
      'Eksporter', 'Bildet er lagret i Bilder!', 'Kunne ikke lagre bildet',
      'Instagram er ikke installert', 'Installer Instagram for å dele.',
      'Kunne ikke dele på Instagram', 'Galleri', 'Filer', 'Del',
    ],
    'Bildet er ikke tilgjengelig',
    ['Varsler', 'Tillat påminnelser i systemets varslingsinnstillinger'],
  ),
  pl: defineUi(
    'Błąd',
    [
      'Duplikuj', 'Zmień nazwę', 'Zmień nazwę projektu', 'Wpisz nazwę projektu',
      'Nazwa nie może być pusta', 'Projekt bez nazwy', 'Miks', 'Elementy: {count}',
      'Przed chwilą', '{count} min temu', '{count} godz. temu', 'Wczoraj', 'Dzisiaj',
      '{count} dni temu', 'Kopia', 'Wybrano: {count}', 'Usuń projekty',
      'Usunąć wybrane projekty ({count})? Tej czynności nie można cofnąć.',
    ],
    [
      'Wybierz zdjęcie', 'Wczytywanie zdjęć...', 'Dostępne zdjęcia: {count}',
      'Wczytywanie Twoich zdjęć...', 'Nie można wczytać zdjęć',
      'Zezwól na dostęp do biblioteki i upewnij się, że zdjęcia są dostępne.',
      'Nie można otworzyć biblioteki zdjęć',
    ],
    [
      'Eksportuj', 'Obraz zapisano w Zdjęciach!', 'Nie udało się zapisać obrazu',
      'Instagram nie jest zainstalowany', 'Zainstaluj Instagram, aby udostępniać.',
      'Nie udało się udostępnić na Instagramie', 'Galeria', 'Pliki', 'Udostępnij',
    ],
    'Obraz jest niedostępny',
    ['Powiadomienia', 'Zezwól na przypomnienia w systemowych ustawieniach powiadomień'],
  ),
  ro: defineUi(
    'Eroare',
    [
      'Duplică', 'Redenumește', 'Redenumește proiectul', 'Introdu numele proiectului',
      'Numele nu poate fi gol', 'Proiect fără titlu', 'Mixat', 'Elemente: {count}',
      'Chiar acum', 'Acum {count} min', 'Acum {count} h', 'Ieri', 'Astăzi',
      'Acum {count} zile', 'Copie', '{count} selectate', 'Șterge proiectele',
      'Ștergi cele {count} proiecte selectate? Acțiunea nu poate fi anulată.',
    ],
    [
      'Selectează fotografia', 'Se încarcă fotografiile...', 'Fotografii disponibile: {count}',
      'Se încarcă fotografiile tale...', 'Fotografiile nu au putut fi încărcate',
      'Permite accesul la bibliotecă și asigură-te că există fotografii disponibile.',
      'Biblioteca foto nu a putut fi deschisă',
    ],
    [
      'Exportă', 'Imagine salvată în Poze!', 'Imaginea nu a putut fi salvată',
      'Instagram nu este instalat', 'Instalează Instagram pentru distribuire.',
      'Distribuirea pe Instagram a eșuat', 'Galerie', 'Fișiere', 'Distribuie',
    ],
    'Imagine indisponibilă',
    ['Notificări', 'Permite mementourile în setările de notificări ale sistemului'],
  ),
  sv: defineUi(
    'Fel',
    [
      'Duplicera', 'Byt namn', 'Byt namn på projekt', 'Ange projektnamn',
      'Namnet får inte vara tomt', 'Namnlöst projekt', 'Mixad', 'Element: {count}',
      'Nyss', 'För {count} min sedan', 'För {count} tim sedan', 'I går', 'I dag',
      'För {count} dagar sedan', 'Kopia', '{count} markerade', 'Radera projekt',
      'Radera de {count} markerade projekten? Detta kan inte ångras.',
    ],
    [
      'Välj foto', 'Läser in foton...', 'Tillgängliga foton: {count}',
      'Läser in dina foton...', 'Det gick inte att läsa in foton',
      'Tillåt åtkomst till bildbiblioteket och kontrollera att foton finns.',
      'Det gick inte att öppna bildbiblioteket',
    ],
    [
      'Exportera', 'Bilden sparades i Bilder!', 'Det gick inte att spara bilden',
      'Instagram är inte installerat', 'Installera Instagram för att dela.',
      'Det gick inte att dela på Instagram', 'Galleri', 'Filer', 'Dela',
    ],
    'Bilden är inte tillgänglig',
    ['Notiser', 'Tillåt påminnelser i systemets notisinställningar'],
  ),
  th: defineUi(
    'ข้อผิดพลาด',
    [
      'ทำสำเนา', 'เปลี่ยนชื่อ', 'เปลี่ยนชื่อโปรเจกต์', 'ป้อนชื่อโปรเจกต์',
      'ชื่อต้องไม่เว้นว่าง', 'โปรเจกต์ไม่มีชื่อ', 'มิกซ์แล้ว', 'องค์ประกอบ: {count}',
      'เมื่อสักครู่', '{count} นาทีที่แล้ว', '{count} ชั่วโมงที่แล้ว', 'เมื่อวาน', 'วันนี้',
      '{count} วันที่แล้ว', 'สำเนา', 'เลือกแล้ว {count}', 'ลบโปรเจกต์',
      'ลบโปรเจกต์ที่เลือก {count} รายการหรือไม่ การดำเนินการนี้ย้อนกลับไม่ได้',
    ],
    [
      'เลือกรูปภาพ', 'กำลังโหลดรูปภาพ...', 'รูปภาพที่ใช้ได้: {count}',
      'กำลังโหลดรูปภาพของคุณ...', 'ไม่สามารถโหลดรูปภาพได้',
      'โปรดอนุญาตการเข้าถึงคลังรูปภาพและตรวจสอบว่ามีรูปภาพอยู่',
      'ไม่สามารถเปิดคลังรูปภาพได้',
    ],
    [
      'ส่งออก', 'บันทึกรูปภาพไปยังแอปรูปภาพแล้ว!', 'ไม่สามารถบันทึกรูปภาพได้',
      'ยังไม่ได้ติดตั้ง Instagram', 'โปรดติดตั้ง Instagram เพื่อแชร์',
      'ไม่สามารถแชร์ไปยัง Instagram ได้', 'แกลเลอรี', 'ไฟล์', 'แชร์',
    ],
    'ไม่มีรูปภาพนี้',
    ['การแจ้งเตือน', 'อนุญาตการเตือนความจำในการตั้งค่าการแจ้งเตือนของระบบ'],
  ),
  tr: defineUi(
    'Hata',
    [
      'Çoğalt', 'Yeniden adlandır', 'Projeyi yeniden adlandır', 'Proje adını girin',
      'Ad boş bırakılamaz', 'Adsız proje', 'Karıştırıldı', 'Öğeler: {count}',
      'Az önce', '{count} dk önce', '{count} sa önce', 'Dün', 'Bugün',
      '{count} gün önce', 'Kopya', '{count} seçildi', 'Projeleri sil',
      'Seçilen {count} proje silinsin mi? Bu işlem geri alınamaz.',
    ],
    [
      'Fotoğraf seç', 'Fotoğraflar yükleniyor...', 'Kullanılabilir fotoğraflar: {count}',
      'Fotoğraflarınız yükleniyor...', 'Fotoğraflar yüklenemedi',
      'Fotoğraf arşivine erişime izin verin ve fotoğrafların bulunduğundan emin olun.',
      'Fotoğraf arşivi açılamadı',
    ],
    [
      'Dışa aktar', 'Görüntü Fotoğraflar’a kaydedildi!', 'Görüntü kaydedilemedi',
      'Instagram yüklü değil', 'Paylaşmak için Instagram’ı yükleyin.',
      'Instagram’da paylaşılamadı', 'Galeri', 'Dosyalar', 'Paylaş',
    ],
    'Görüntü kullanılamıyor',
    ['Bildirimler', 'Sistem bildirim ayarlarında hatırlatıcılara izin verin'],
  ),
  vi: defineUi(
    'Lỗi',
    [
      'Nhân bản', 'Đổi tên', 'Đổi tên dự án', 'Nhập tên dự án',
      'Tên không được để trống', 'Dự án chưa đặt tên', 'Đã phối', 'Thành phần: {count}',
      'Vừa xong', '{count} phút trước', '{count} giờ trước', 'Hôm qua', 'Hôm nay',
      '{count} ngày trước', 'Bản sao', 'Đã chọn {count}', 'Xóa dự án',
      'Xóa {count} dự án đã chọn? Không thể hoàn tác thao tác này.',
    ],
    [
      'Chọn ảnh', 'Đang tải ảnh...', 'Ảnh có sẵn: {count}',
      'Đang tải ảnh của bạn...', 'Không thể tải ảnh',
      'Hãy cho phép truy cập thư viện ảnh và đảm bảo có ảnh trong thư viện.',
      'Không thể mở thư viện ảnh',
    ],
    [
      'Xuất', 'Đã lưu ảnh vào Ảnh!', 'Không thể lưu ảnh',
      'Chưa cài đặt Instagram', 'Hãy cài đặt Instagram để chia sẻ.',
      'Không thể chia sẻ lên Instagram', 'Thư viện', 'Tệp', 'Chia sẻ',
    ],
    'Không có ảnh',
    ['Thông báo', 'Cho phép lời nhắc trong cài đặt thông báo hệ thống'],
  ),
};
