/**
 * Effect registry - defines all available effects
 */

import { Effect, EffectCategory } from './types';

export const EFFECTS: Effect[] = [
  // CELLULAR EFFECTS
  {
    id: 'pixelate',
    name: 'Pixelate',
    category: EffectCategory.CELLULAR,
    description: 'Classic pixel mosaic effect',
    isPremium: false,
    complexity: 0.2,
    icon: require('../../assets/icons/filters/pixelate_strong.png'),
    parameters: [
      {
        name: 'cellSize',
        label: 'Cell Size',
        type: 'slider',
        min: 2,
        max: 100,
        default: 10,
        step: 1,
      },
      {
        name: 'shape',
        label: 'Shape',
        type: 'segmented',
        options: ['Square', 'Circle', 'Diamond'],
        default: 'Square',
      },
    ],
    shaderPath: 'cellular/pixelate.sksl',
  },
  {
    id: 'crystallize',
    name: 'Crystallize',
    category: EffectCategory.CELLULAR,
    description: 'Voronoi cell-based effect',
    isPremium: true,
    complexity: 0.6,
    icon: require('../../assets/icons/filters/stained_glass_strong.png'),
    parameters: [
      {
        name: 'cellCount',
        label: 'Cell Count',
        type: 'slider',
        min: 10,
        max: 500,
        default: 100,
        step: 10,
      },
      {
        name: 'randomSeed',
        label: 'Random Seed',
        type: 'slider',
        min: 0,
        max: 1000,
        default: 42,
        step: 1,
      },
    ],
  },
  {
    id: 'halftone',
    name: 'Halftone',
    category: EffectCategory.CELLULAR,
    description: 'Classic print halftone dots',
    isPremium: true,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/halftone_dots_strong.png'),
    parameters: [
      {
        name: 'dotSize',
        label: 'Dot Size',
        type: 'slider',
        min: 2,
        max: 30,
        default: 8,
        step: 1,
      },
      {
        name: 'angle',
        label: 'Angle',
        type: 'slider',
        min: 0,
        max: 90,
        default: 45,
        step: 1,
      },
    ],
    shaderPath: 'cellular/halftone.sksl',
  },
  {
    id: 'pointillize',
    name: 'Pointillize',
    category: EffectCategory.CELLULAR,
    description: 'Pointillist painting effect',
    isPremium: true,
    complexity: 0.6,
    icon: require('../../assets/icons/filters/pointillize_strong.png'),
    parameters: [
      {
        name: 'dotSize',
        label: 'Dot Size',
        type: 'slider',
        min: 2,
        max: 30,
        default: 8,
        step: 1,
      },
    ],
  },

  // TILING EFFECTS
  {
    id: 'kaleidoscope',
    name: 'Kaleidoscope',
    category: EffectCategory.TILING,
    description: 'Radial symmetry effect',
    isPremium: false,
    complexity: 0.3,
    icon: require('../../assets/icons/filters/quad_mirror.png'),
    parameters: [
      {
        name: 'segments',
        label: 'Segments',
        type: 'slider',
        min: 2,
        max: 24,
        default: 6,
        step: 1,
      },
      {
        name: 'angle',
        label: 'Rotation',
        type: 'slider',
        min: 0,
        max: 360,
        default: 0,
        step: 1,
      },
      {
        name: 'zoom',
        label: 'Zoom',
        type: 'slider',
        min: 0.5,
        max: 3,
        default: 1,
        step: 0.1,
      },
    ],
    shaderPath: 'tiling/kaleidoscope.sksl',
  },
  {
    id: 'mirror',
    name: 'Mirror',
    category: EffectCategory.TILING,
    description: 'Mirror reflection effect',
    isPremium: false,
    complexity: 0.2,
    icon: require('../../assets/icons/filters/quad_mirror.png'),
    parameters: [
      {
        name: 'axis',
        label: 'Axis',
        type: 'segmented',
        options: ['Horizontal', 'Vertical', 'Both', 'Diagonal'],
        default: 'Horizontal',
      },
      {
        name: 'offset',
        label: 'Offset',
        type: 'slider',
        min: -1,
        max: 1,
        default: 0,
        step: 0.01,
      },
    ],
    shaderPath: 'tiling/mirror.sksl',
  },
  {
    id: 'tile',
    name: 'Tile Offset',
    category: EffectCategory.TILING,
    description: 'Tiling offset effect',
    isPremium: false,
    complexity: 0.2,
    icon: require('../../assets/icons/filters/tile_offset_big.png'),
    parameters: [
      {
        name: 'offsetX',
        label: 'Offset X',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
      {
        name: 'offsetY',
        label: 'Offset Y',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
  },

  // DISTORTION EFFECTS
  {
    id: 'wave',
    name: 'Wave',
    category: EffectCategory.DISTORTION,
    description: 'Sinusoidal wave distortion',
    isPremium: false,
    complexity: 0.3,
    icon: require('../../assets/icons/filters/ripple_sine_strong.png'),
    parameters: [
      {
        name: 'amplitude',
        label: 'Amplitude',
        type: 'slider',
        min: 0,
        max: 100,
        default: 20,
        step: 1,
      },
      {
        name: 'frequency',
        label: 'Frequency',
        type: 'slider',
        min: 0.1,
        max: 10,
        default: 2,
        step: 0.1,
      },
      {
        name: 'phase',
        label: 'Phase',
        type: 'slider',
        min: 0,
        max: 360,
        default: 0,
        step: 1,
      },
      {
        name: 'direction',
        label: 'Direction',
        type: 'segmented',
        options: ['Horizontal', 'Vertical', 'Radial'],
        default: 'Horizontal',
      },
    ],
    shaderPath: 'distortion/wave.sksl',
  },
  {
    id: 'twirl',
    name: 'Twirl',
    category: EffectCategory.DISTORTION,
    description: 'Spiral rotation effect',
    isPremium: true,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/swirl_strong.png'),
    parameters: [
      {
        name: 'angle',
        label: 'Angle',
        type: 'slider',
        min: -720,
        max: 720,
        default: 180,
        step: 10,
      },
      {
        name: 'radius',
        label: 'Radius',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
    shaderPath: 'distortion/twirl.sksl',
  },
  {
    id: 'bulge',
    name: 'Bulge/Pinch',
    category: EffectCategory.DISTORTION,
    description: 'Radial scale distortion',
    isPremium: true,
    complexity: 0.3,
    icon: require('../../assets/icons/filters/bulge_strong.png'),
    parameters: [
      {
        name: 'strength',
        label: 'Strength',
        type: 'slider',
        min: -1,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
      {
        name: 'radius',
        label: 'Radius',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
    shaderPath: 'distortion/bulge.sksl',
  },
  {
    id: 'pinch',
    name: 'Pinch',
    category: EffectCategory.DISTORTION,
    description: 'Pinch distortion effect',
    isPremium: true,
    complexity: 0.3,
    icon: require('../../assets/icons/filters/pinch_strong.png'),
    parameters: [
      {
        name: 'strength',
        label: 'Strength',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
    shaderPath: 'distortion/pinch.sksl',
  },
  {
    id: 'spherize',
    name: 'Spherize',
    category: EffectCategory.DISTORTION,
    description: 'Spherical distortion',
    isPremium: true,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/spherize_strong.png'),
    parameters: [
      {
        name: 'strength',
        label: 'Strength',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
    shaderPath: 'distortion/spherize.sksl',
  },
  {
    id: 'shear',
    name: 'Shear',
    category: EffectCategory.DISTORTION,
    description: 'Affine shear transform',
    isPremium: false,
    complexity: 0.2,
    icon: require('../../assets/icons/filters/shear_affine_strong.png'),
    parameters: [
      {
        name: 'angle',
        label: 'Angle',
        type: 'slider',
        min: -45,
        max: 45,
        default: 15,
        step: 1,
      },
    ],
    shaderPath: 'distortion/shear.sksl',
  },
  {
    id: 'noise-displace',
    name: 'Noise Displace',
    category: EffectCategory.DISTORTION,
    description: 'Random noise displacement',
    isPremium: true,
    complexity: 0.6,
    icon: require('../../assets/icons/filters/noise_displace_strong.png'),
    parameters: [
      {
        name: 'amount',
        label: 'Amount',
        type: 'slider',
        min: 0,
        max: 100,
        default: 20,
        step: 1,
      },
    ],
    shaderPath: 'distortion/noise-displace.sksl',
  },

  // GLITCH EFFECTS
  {
    id: 'rgb-split',
    name: 'RGB Split',
    category: EffectCategory.GLITCH,
    description: 'Chromatic aberration effect',
    isPremium: false,
    complexity: 0.2,
    icon: require('../../assets/icons/filters/rgb_split_big.png'),
    parameters: [
      {
        name: 'offsetX',
        label: 'Offset X',
        type: 'slider',
        min: -50,
        max: 50,
        default: 10,
        step: 1,
      },
      {
        name: 'offsetY',
        label: 'Offset Y',
        type: 'slider',
        min: -50,
        max: 50,
        default: 0,
        step: 1,
      },
    ],
    shaderPath: 'glitch/rgb-split.sksl',
  },
  {
    id: 'scanlines',
    name: 'Scanlines',
    category: EffectCategory.GLITCH,
    description: 'CRT monitor effect',
    isPremium: false,
    complexity: 0.2,
    icon: require('../../assets/icons/filters/scanlines_dark.png'),
    parameters: [
      {
        name: 'lineCount',
        label: 'Line Count',
        type: 'slider',
        min: 100,
        max: 1000,
        default: 300,
        step: 10,
      },
      {
        name: 'opacity',
        label: 'Opacity',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
    shaderPath: 'glitch/scanlines.sksl',
  },
  {
    id: 'glitch-rows',
    name: 'Glitch Rows',
    category: EffectCategory.GLITCH,
    description: 'Horizontal glitch rows',
    isPremium: true,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/glitch_rows_heavy.png'),
    parameters: [
      {
        name: 'amount',
        label: 'Amount',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
  },

  // RELIEF EFFECTS
  {
    id: 'emboss',
    name: 'Emboss',
    category: EffectCategory.RELIEF,
    description: '3D raised surface effect',
    isPremium: true,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/emboss.png'),
    parameters: [
      {
        name: 'angle',
        label: 'Light Angle',
        type: 'slider',
        min: 0,
        max: 360,
        default: 135,
        step: 1,
      },
      {
        name: 'height',
        label: 'Height',
        type: 'slider',
        min: 0,
        max: 10,
        default: 3,
        step: 0.1,
      },
    ],
    shaderPath: 'relief/emboss.sksl',
  },
  {
    id: 'bevel',
    name: 'Bevel',
    category: EffectCategory.RELIEF,
    description: 'Bevel and relief effect',
    isPremium: true,
    complexity: 0.5,
    icon: require('../../assets/icons/filters/bevel_relief_heavy.png'),
    parameters: [
      {
        name: 'depth',
        label: 'Depth',
        type: 'slider',
        min: 0,
        max: 10,
        default: 3,
        step: 0.1,
      },
    ],
  },
  {
    id: 'find-edges',
    name: 'Find Edges',
    category: EffectCategory.RELIEF,
    description: 'Edge detection effect',
    isPremium: false,
    complexity: 0.3,
    icon: require('../../assets/icons/filters/find_edges.png'),
    parameters: [
      {
        name: 'threshold',
        label: 'Threshold',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
  },

  // STYLIZATION EFFECTS
  {
    id: 'oil-paint',
    name: 'Oil Paint',
    category: EffectCategory.STYLIZATION,
    description: 'Painted appearance',
    isPremium: true,
    complexity: 0.8,
    icon: require('../../assets/icons/filters/oil_paintish_bold.png'),
    parameters: [
      {
        name: 'brushSize',
        label: 'Brush Size',
        type: 'slider',
        min: 1,
        max: 20,
        default: 5,
        step: 1,
      },
      {
        name: 'detail',
        label: 'Detail',
        type: 'slider',
        min: 1,
        max: 10,
        default: 5,
        step: 1,
      },
    ],
    shaderPath: 'stylization/oil-paint.sksl',
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    category: EffectCategory.STYLIZATION,
    description: 'Watercolor painting effect',
    isPremium: true,
    complexity: 0.7,
    icon: require('../../assets/icons/filters/watercolor_bold.png'),
    parameters: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
  },
  {
    id: 'posterize',
    name: 'Posterize',
    category: EffectCategory.STYLIZATION,
    description: 'Color quantization effect',
    isPremium: false,
    complexity: 0.2,
    icon: require('../../assets/icons/filters/posterize_3bit.png'),
    parameters: [
      {
        name: 'levels',
        label: 'Levels',
        type: 'slider',
        min: 2,
        max: 16,
        default: 4,
        step: 1,
      },
    ],
  },
  {
    id: 'poster-edges',
    name: 'Poster Edges',
    category: EffectCategory.STYLIZATION,
    description: 'Posterized edges effect',
    isPremium: true,
    complexity: 0.5,
    icon: require('../../assets/icons/filters/poster_edges_bold.png'),
    parameters: [
      {
        name: 'edge',
        label: 'Edge Intensity',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
  },

  // BLUR & SHARPEN EFFECTS
  {
    id: 'gaussian-blur',
    name: 'Gaussian Blur',
    category: EffectCategory.BLUR_SHARPEN,
    description: 'Soft Gaussian blur with adjustable radius',
    isPremium: false,
    complexity: 0.3,
    icon: require('../../assets/icons/filters/icon_effects_A/Gaussian_Blur.png'),
    parameters: [
      {
        name: 'radius',
        label: 'Radius',
        type: 'slider',
        min: 0,
        max: 50,
        default: 10,
        step: 1,
      },
      {
        name: 'quality',
        label: 'Quality',
        type: 'slider',
        min: 1,
        max: 3,
        default: 2,
        step: 1,
      },
    ],
  },
  {
    id: 'motion-blur',
    name: 'Motion Blur',
    category: EffectCategory.BLUR_SHARPEN,
    description: 'Directional motion blur',
    isPremium: true,
    complexity: 0.5,
    icon: require('../../assets/icons/filters/icon_effects_A/Motion_Blur.png'),
    parameters: [
      {
        name: 'distance',
        label: 'Distance',
        type: 'slider',
        min: 0,
        max: 100,
        default: 25,
        step: 1,
      },
      {
        name: 'angle',
        label: 'Angle',
        type: 'slider',
        min: 0,
        max: 360,
        default: 0,
        step: 1,
      },
    ],
  },
  {
    id: 'surface-blur',
    name: 'Surface Blur',
    category: EffectCategory.BLUR_SHARPEN,
    description: 'Edge-preserving blur for surfaces',
    isPremium: true,
    complexity: 0.6,
    icon: require('../../assets/icons/filters/icon_effects_A/Surface_Blur.png'),
    parameters: [
      {
        name: 'radius',
        label: 'Radius',
        type: 'slider',
        min: 1,
        max: 40,
        default: 12,
        step: 1,
      },
      {
        name: 'threshold',
        label: 'Threshold',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.2,
        step: 0.01,
      },
    ],
    shaderPath: 'blur/surface-blur.sksl',
  },
  {
    id: 'unsharp-mask',
    name: 'Unsharp Mask',
    category: EffectCategory.BLUR_SHARPEN,
    description: 'Sharpen details using unsharp masking',
    isPremium: false,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/icon_effects_A/Unsharp_Sharpen.png'),
    parameters: [
      {
        name: 'amount',
        label: 'Amount',
        type: 'slider',
        min: 0,
        max: 2,
        default: 0.6,
        step: 0.01,
      },
      {
        name: 'radius',
        label: 'Radius',
        type: 'slider',
        min: 1,
        max: 30,
        default: 8,
        step: 1,
      },
    ],
    shaderPath: 'blur/unsharp-mask.sksl',
  },

  // ARTISTIC BRUSH EFFECTS
  {
    id: 'accented-edges',
    name: 'Accented Edges',
    category: EffectCategory.BRUSH,
    description: 'Enhance and accentuate edges for sketch look',
    isPremium: false,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/icon_effects_A/Accented_Edges.png'),
    parameters: [
      {
        name: 'strength',
        label: 'Strength',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
      {
        name: 'threshold',
        label: 'Threshold',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.3,
        step: 0.01,
      },
    ],
  },
  {
    id: 'cross-hatch',
    name: 'Cross Hatch',
    category: EffectCategory.BRUSH,
    description: 'Layered hatch strokes based on luminance',
    isPremium: true,
    complexity: 0.6,
    icon: require('../../assets/icons/filters/icon_effects_A/Cross_Hatch.png'),
    parameters: [
      {
        name: 'density',
        label: 'Density',
        type: 'slider',
        min: 0.1,
        max: 2,
        default: 1,
        step: 0.1,
      },
      {
        name: 'rotation',
        label: 'Rotation',
        type: 'slider',
        min: 0,
        max: 90,
        default: 45,
        step: 1,
      },
    ],
  },
  {
    id: 'ink-outlines',
    name: 'Ink Outlines',
    category: EffectCategory.BRUSH,
    description: 'Bold ink outlines with smooth fill',
    isPremium: true,
    complexity: 0.5,
    icon: require('../../assets/icons/filters/icon_effects_A/Ink_Outlines.png'),
    parameters: [
      {
        name: 'threshold',
        label: 'Threshold',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.4,
        step: 0.01,
      },
      {
        name: 'smoothness',
        label: 'Smoothness',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.3,
        step: 0.01,
      },
    ],
  },
  {
    id: 'spatter',
    name: 'Spatter',
    category: EffectCategory.BRUSH,
    description: 'Randomized sprayed strokes',
    isPremium: true,
    complexity: 0.5,
    icon: require('../../assets/icons/filters/icon_effects_A/Spatter_Sprayed.png'),
    parameters: [
      {
        name: 'density',
        label: 'Density',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
      {
        name: 'size',
        label: 'Drop Size',
        type: 'slider',
        min: 1,
        max: 30,
        default: 10,
        step: 1,
      },
    ],
  },
  {
    id: 'sumi-e',
    name: 'Sumi-e',
    category: EffectCategory.BRUSH,
    description: 'Monochrome japanese ink wash look',
    isPremium: true,
    complexity: 0.6,
    icon: require('../../assets/icons/filters/icon_effects_A/Sumi_e.png'),
    parameters: [
      {
        name: 'ink',
        label: 'Ink Flow',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.6,
        step: 0.01,
      },
      {
        name: 'wash',
        label: 'Wash',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.4,
        step: 0.01,
      },
    ],
  },
  {
    id: 'plastic-wrap',
    name: 'Plastic Wrap',
    category: EffectCategory.BRUSH,
    description: 'Glossy highlights like plastic wrap',
    isPremium: true,
    complexity: 0.6,
    icon: require('../../assets/icons/filters/icon_effects_A/Plastic_Wrap.png'),
    parameters: [
      {
        name: 'highlight',
        label: 'Highlight',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.7,
        step: 0.01,
      },
      {
        name: 'detail',
        label: 'Detail',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.4,
        step: 0.01,
      },
    ],
  },
  {
    id: 'clouds-fibers',
    name: 'Clouds & Fibers',
    category: EffectCategory.BRUSH,
    description: 'Procedural clouds and fibers texture',
    isPremium: false,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/icon_effects_A/Clouds.png'),
    parameters: [
      {
        name: 'scale',
        label: 'Scale',
        type: 'slider',
        min: 0.5,
        max: 5,
        default: 2,
        step: 0.1,
      },
      {
        name: 'contrast',
        label: 'Contrast',
        type: 'slider',
        min: 0,
        max: 2,
        default: 1,
        step: 0.01,
      },
    ],
  },


  // DISTORTION & CORRECTION EFFECTS
  {
    id: 'liquify',
    name: 'Liquify',
    category: EffectCategory.CORRECTION,
    description: 'Organic liquify distortion',
    isPremium: true,
    complexity: 0.7,
    icon: require('../../assets/icons/filters/icon_effects_A/Liquify_Swirl.png'),
    parameters: [
      {
        name: 'amount',
        label: 'Amount',
        type: 'slider',
        min: -1,
        max: 1,
        default: 0.4,
        step: 0.01,
      },
      {
        name: 'radius',
        label: 'Radius',
        type: 'slider',
        min: 0.1,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
    ],
  },
  {
    id: 'lens-correction',
    name: 'Lens Correction',
    category: EffectCategory.CORRECTION,
    description: 'Adjust barrel or pincushion lens distortion',
    isPremium: false,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/icon_effects_A/Lens_Correction_Barrel.png'),
    parameters: [
      {
        name: 'distortion',
        label: 'Distortion',
        type: 'slider',
        min: -1,
        max: 1,
        default: -0.2,
        step: 0.01,
      },
      {
        name: 'center',
        label: 'Center Offset',
        type: 'slider',
        min: -0.5,
        max: 0.5,
        default: 0,
        step: 0.01,
      },
    ],
  },

  // FREQUENCY DOMAIN EFFECTS
  {
    id: 'high-pass',
    name: 'High-Pass Filter',
    category: EffectCategory.FREQUENCY,
    description: 'Emphasize high-frequency detail',
    isPremium: false,
    complexity: 0.5,
    icon: require('../../assets/icons/filters/icon_effects_A/High_Pass_Sharpen.png'),
    parameters: [
      {
        name: 'radius',
        label: 'Radius',
        type: 'slider',
        min: 1,
        max: 40,
        default: 12,
        step: 1,
      },
      {
        name: 'amount',
        label: 'Amount',
        type: 'slider',
        min: 0,
        max: 2,
        default: 0.8,
        step: 0.01,
      },
    ],
  },
  {
    id: 'low-pass',
    name: 'Low-Pass Filter',
    category: EffectCategory.FREQUENCY,
    description: 'Remove high-frequency noise',
    isPremium: false,
    complexity: 0.4,
    icon: require('../../assets/icons/filters/icon_effects_A/Low_Pass_Blur.png'),
    parameters: [
      {
        name: 'radius',
        label: 'Radius',
        type: 'slider',
        min: 1,
        max: 50,
        default: 18,
        step: 1,
      },
    ],
  },
  {
    id: 'gradient-filter',
    name: 'Gradient Filter',
    category: EffectCategory.FREQUENCY,
    description: 'Directional gradient emphasis',
    isPremium: true,
    complexity: 0.5,
    icon: require('../../assets/icons/filters/icon_effects_A/Gradient_Filter_Map.png'),
    parameters: [
      {
        name: 'angle',
        label: 'Angle',
        type: 'slider',
        min: 0,
        max: 360,
        default: 45,
        step: 1,
      },
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.6,
        step: 0.01,
      },
    ],
  },
  {
    id: 'fourier-mask',
    name: 'Fourier Mask',
    category: EffectCategory.FREQUENCY,
    description: 'Frequency domain style mask',
    isPremium: true,
    complexity: 0.7,
    icon: require('../../assets/icons/filters/icon_effects_A/Fourier_Lowpass.png'),
    parameters: [
      {
        name: 'band',
        label: 'Band',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.5,
        step: 0.01,
      },
      {
        name: 'contrast',
        label: 'Contrast',
        type: 'slider',
        min: 0,
        max: 2,
        default: 1,
        step: 0.01,
      },
    ],
  },

  // RENDER EFFECTS
  {
    id: 'flame-render',
    name: 'Flame',
    category: EffectCategory.RENDER,
    description: 'Procedural flame-like energy overlay',
    isPremium: true,
    complexity: 0.7,
    icon: require('../../assets/icons/filters/icon_effects_A/Flame_Render.png'),
    parameters: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'slider',
        min: 0,
        max: 1,
        default: 0.7,
        step: 0.01,
      },
      {
        name: 'detail',
        label: 'Detail',
        type: 'slider',
        min: 0.5,
        max: 4,
        default: 1.5,
        step: 0.1,
      },
    ],
  },
  {
    id: 'render-clouds',
    name: 'Render Clouds',
    category: EffectCategory.RENDER,
    description: 'Procedural soft clouds overlay',
    isPremium: false,
    complexity: 0.6,
    icon: require('../../assets/icons/filters/icon_effects_A/Render_Clouds.png'),
    parameters: [
      {
        name: 'scale',
        label: 'Scale',
        type: 'slider',
        min: 0.5,
        max: 5,
        default: 1.5,
        step: 0.1,
      },
      {
        name: 'contrast',
        label: 'Contrast',
        type: 'slider',
        min: 0,
        max: 2,
        default: 0.8,
        step: 0.01,
      },
    ],
  },
];

export const getEffectById = (id: string): Effect | undefined => {
  return EFFECTS.find(effect => effect.id === id);
};

export const getEffectsByCategory = (category: EffectCategory): Effect[] => {
  return EFFECTS.filter(effect => effect.category === category);
};

export const getFreeEffects = (): Effect[] => {
  return EFFECTS.filter(effect => !effect.isPremium);
};
